name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
      
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
           
      - name: Get version
        run: |
          versionVar=$(mvn help:evaluate -Dexpression='project.version' -q -DforceStdout --file ./maven-github-action/pom.xml )
          echo "::set-env name=artifactVersion::$versionVar"

      - name: Show version
        run: echo $artifactVersion  

      - name: Build with Maven
        run: mvn -B package --file ./maven-github-action/pom.xml  

      - uses: actions/upload-artifact@v2
        with:
          name: maven-github-action-${{ env.artifactVersion }} 
          path: ./maven-github-action/target/app.jar          

      
