name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  env-test:
    runs-on: ubuntu-latest
    
    env:
        SERVER: $TEST_SERVER

    steps:
      - uses: actions/checkout@v2

      - name: Nome do comando
        run: echo "$SERVER"

      
